### ISSUE TITLE
Float 16 vs 32 comparison

### ISSUE THREAD

**Issue by sivagnanamn** [digitalbrain79/darknet-nnpack#16]
Currently does this execute YOLO with 32bit or 16 bit precision? Is there an option to change the precision and benchmark?

**Comment by digitalbrain79** [comment]
Only support 32bit precision.

**Comment by sivagnanamn** [comment]
Were you able to find the reason for Tiny YOLO network not producing the predictions? If not please give some pointers where to look in the code for getting it to work
