### ISSUE TITLE
Update for Darknet YOLO version 3

### ISSUE THREAD

**Issue by spinoza1791** [digitalbrain79/darknet-nnpack#19]
Will you be updating darknet-nnpack to make use of new features in YOLOv3 today?  https://github.com/pjreddie/darknet

**Comment by digitalbrain79** [comment]
Yes, I will try it.

**Comment by digitalbrain79** [comment]
@spinoza1791 I added branch yolov3. But it is not work (killed with segmentation fault). I think Raspberry Pi 3's memory is not sufficient to run YOLOv3.

**Comment by ljh14** [comment]
Is there any solution to make yolov3 run on Rpi3?

**Comment by spinoza1791** [comment]
do you have yolov3 NNPack Darknet working for any CPU?  Do you think the
seg fault is only for Pi?

**Comment by digitalbrain79** [comment]
@spinoza1791 yolov3 run well on Intel I7 CPU. If you want run yolov3 on Intel CPU, you should set ARM_NEON=0 in makefile. I did not test other CPUs except Intel I7 and RPI3.

**Comment by spinoza1791** [comment]
There are new files in current darknet which are not in your repo.  Such as znorm_layer.c/.h, logistic_layer.c/h, unsample_layer.c/h and yolo_layer.c/h.  You will need to include these to take advantage of new yolo features.  Will you be updating NNPack/darknet to include these?

**Comment by spinoza1791** [comment]
when using the upsample layer i get "type not recognized: [upsample]'  How is are you getting NNPack to work without the unsample_layer.c/h in your repo?

**Comment by digitalbrain79** [comment]
@spinoza1791 Did you change branch to yolov3? (git checkout yolov3)
I cannot find znorm_layer.c/.h and unsample_layer.c/h in original darknet repo.

**Comment by spinoza1791** [comment]
Here's a link to the current yolo repo, updated 27 days ago for the upsample.c
https://github.com/pjreddie/darknet/tree/master/src

**Comment by spinoza1791** [comment]
'git checkout yolov3' works with upsample:)  Thank you!

**Comment by shartoo** [comment]
If you write a yolov3 from [AlexeyAB darkent](https://github.com/AlexeyAB/darknet) other than [pjreddie darknet](https://github.com/pjreddie/darknet) ,it will works.The fatal error origins from [pjreddie darknet](https://github.com/pjreddie/darknet).

**Comment by isgursoy** [comment]
https://github.com/digitalbrain79/darknet-nnpack/issues/28
