### ISSUE TITLE
Import error: No module named confu

### ISSUE THREAD

**Issue by phongnhhn92** [digitalbrain79/darknet-nnpack#22]
Hi guys, I am trying to build the darknet-nnpack but my rasberry pi can not find confu at this step.
`python ./configure.py --backend auto`
 This is the error:
`Traceback (most recent call last):
  File "./configure.py", line 4, in <module>
    import confu
ImportError: No module named confu
`
I run the previous command `confu setup` with no problem so I guess I installed confu already.
Please help me !

**Comment by mouminali97** [comment]
I have the same problem!

**Comment by phongnhhn92** [comment]
I found my solution.
In my raspberry pi 3, confu is installed in python3 not python2. So I edit the command a bit 
`python3 ./configure.py --backend auto`
It works flawlessly !

**Comment by mouminali97** [comment]
Yes it worked now. Thank you so much!

**Comment by mouminali97** [comment]
$NINJA_PATH/ninja
sudo cp -a lib/* /usr/lib/
sudo cp include/nnpack.h /usr/include/
sudo cp deps/pthreadpool/include/pthreadpool.h /usr/include/

what exactly is this as I am getting an error for this...it says no such file or directory

**Comment by phongnhhn92** [comment]
For me the next step is just simply type command ninja so that the NNpack can be built. After that you should be able to copy all the header and library files.

**Comment by Rishan123** [comment]
> I found my solution.
> In my raspberry pi 3, confu is installed in python3 not python2. So I edit the command a bit
> `python3 ./configure.py --backend auto`
> It works flawlessly !

I now got the error of:

`Usage: configure.py [options]
configure.py: error: no such option: --backend`

**Comment by aidamanzano** [comment]
> I found my solution.
> In my raspberry pi 3, confu is installed in python3 not python2. So I edit the command a bit
> `python3 ./configure.py --backend auto`
> It works flawlessly !

Hi I tried this and I get this error instaed:`Traceback (most recent call last):
  File "./configure.py", line 4, in <module>
    import confu
ModuleNotFoundError: No module named 'confu'`
Anyone managed to fix this issue? I'm using a Raspberry Pi 4 and Raspbian Buster
