### ISSUE TITLE
$NINJA_PATH/ninja

### ISSUE THREAD

**Issue by mouminali97** [digitalbrain79/darknet-nnpack#23]
$NINJA_PATH/ninja
sudo cp -a lib/* /usr/lib/
sudo cp include/nnpack.h /usr/include/
sudo cp deps/pthreadpool/include/pthreadpool.h /usr/include/

what exactly is this?... I am getting an error message - no such file or directory

**Comment by panban-ux** [comment]
What the $NINJA_PATH/ninja does and how we implement it.?
I'm asking as I cant make(compile) the darknet nnpack folder. I get an error in Pi4b 4gb.
So far the steps behind seem completed except the $NINJA_PATH/ninja which I don't understand
